version: "3.8"

services:
  database:
    image: mysql:5.7
    container_name: payhere-db
    volumes:
      - ./_db/etc/mysql/conf.d:/etc/mysql/conf.d
      # - ./db/var/lib/mysql:/var/lib/mysql
      - ./_db/initdb.d:/docker-entrypoint-initdb.d
    env_file: env
    ports:
      - "3306:3306"

  redis:
    build:
      context: ./_redis
      dockerfile: ./Dockerfile
    container_name: payhere-redis
    command: ["./wait-for", "database:3306", "--", "redis-server", "--port", "6379"]
    hostname: redis-host
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"

  application:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: payhere-app
    command: ["./wait-for", "redis:6379", "--", "java", "-jar","-Dserver.port=8080", "/app.jar"]
    env_file: env
    ports:
      - "8080:8080"
    depends_on:
      - database
      - redis
