version: "3.8"

services:
  database:
    image: mysql:5.7
    container_name: payhere-db
    volumes:
      - ./db/etc/mysql/conf.d:/etc/mysql/conf.d
      - ./db/var/lib/mysql:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: env
    ports:
      - "3306:3306"

  application:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: payhere
    container_name: payhere-app
    command: ["./wait-for", "database:3306", "--", "java", "-jar", "/app.jar"]
    env_file: env
    environment:
      - PAYHERE_DB_IP=database
      - PAYHERE_DB_PORT=3306
    ports:
      - "8080:8080"
    depends_on:
      - database
